apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: nexuspay
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: notification-service
          image: nexuspay/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3004
          env:
            - name: PORT
              value: '3004'
          envFrom:
            - configMapRef:
                name: nexuspay-config
            - secretRef:
                name: nexuspay-secrets
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 250m
              memory: 192Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
